/**
 * AI Integration - OpenRouter Only
 */

import { Env, Activity, Transcript } from './types';

// Helper: Call OpenRouter API
async function callOpenRouter(prompt: string, apiKey: string, model: string): Promise<string> {
    const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';

    if (!apiKey) {
        throw new Error('OpenRouter API key not configured');
    }

    const response = await fetch(OPENROUTER_API_URL, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`,
            'HTTP-Referer': 'https://monitorwatch.app',
            'X-Title': 'MonitorWatch',
        },
        body: JSON.stringify({
            model: model,
            messages: [{ role: 'user', content: prompt }],
            temperature: 0.7,
            max_tokens: 4096,
        }),
    });

    if (!response.ok) {
        const error = await response.text();
        console.error('OpenRouter API Error:', error);
        throw new Error(`OpenRouter API error: ${response.status} - ${error}`);
    }

    const data = await response.json() as any;
    const text = data.choices?.[0]?.message?.content;

    if (!text) {
        throw new Error('No content in OpenRouter response');
    }

    return text;
}


export async function generateNoteWithAI(
    activities: Activity[],
    transcripts: Transcript[],
    date: string,
    env: Env,
    aiConfig?: { provider: string; openRouterKey?: string; model?: string; language?: string },
    noteNumber?: number,
    hourlySummaries?: { hour: number; summary: string }[]
): Promise<string> {
    const language = aiConfig?.language || 'en';
    const model = aiConfig?.model || 'google/gemini-2.0-flash-001';
    const apiKey = aiConfig?.openRouterKey || '';

    // If we have pre-processed hourly summaries, use them
    if (hourlySummaries && hourlySummaries.length > 0) {
        const prompt = buildPromptFromSummaries(hourlySummaries, date, language, noteNumber);
        return await callOpenRouter(prompt, apiKey, model);
    }

    // Fallback to raw data
    const prompt = buildPrompt(activities, transcripts, date, language, noteNumber);
    return await callOpenRouter(prompt, apiKey, model);
}

function buildPromptFromSummaries(summaries: { hour: number; summary: string }[], date: string, language: string, noteNumber?: number): string {
    const locale = language === 'pt' ? 'pt-BR' : 'en-US';
    const formattedDate = new Date(date).toLocaleDateString(locale);

    let summariesText = '';
    for (const s of summaries) {
        const hourStr = `${s.hour.toString().padStart(2, '0')}:00`;
        summariesText += `\n### ${hourStr}\n${s.summary}\n`;
    }

    if (language === 'pt') {
        return buildPortuguesePromptFromSummaries(formattedDate, summariesText, noteNumber);
    }
    return buildEnglishPromptFromSummaries(formattedDate, summariesText, noteNumber);
}

function buildEnglishPromptFromSummaries(formattedDate: string, summariesText: string, noteNumber?: number): string {
    const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19);
    const noteNumberStr = noteNumber ? ` #${noteNumber}` : '';
    
    return `
# GENERATION INSTRUCTIONS

You are a personal assistant integrated with Obsidian.
Create a comprehensive daily note from the hourly summaries below.

## HOURLY SUMMARIES
${summariesText}

---

## OUTPUT FORMAT (MARKDOWN)

Generate only the Markdown content below, no conversation.

**TITLE FORMAT:**
# <Main Subject/Theme of the Day>${noteNumberStr}

*${formattedDate} - Generated: ${generatedAt}*

The title must describe the MAIN focus of the day based on the summaries. Examples:
- "MonitorWatch Development & Testing"
- "Backend Refactoring Session"
- "Client Meetings & Project Planning"
NOT generic like "Daily Log" or "Diary".

## Summary
<Detailed narrative about the day covering all activities, projects, learnings, and conversations. Use tags (#project, #tech) and links ([[Link]]) naturally within sentences.>

## Deliverables & Focus
> [!SUCCESS] Highlights
> - [x] <Achievement 1>
> - [x] <Achievement 2>
> - [x] <More achievements based on the summaries>

### Projects & Tasks
- **<Project Name>**: <What was done>
- **<Another Project>**: <Details>

## Meetings & Insights
> [!quote] Conversations
> <Summary of meetings and conversations if any>

## Learning
- [[Concept]] studied.
- #tech/topic explored.
- <More learnings>

## Reflection
> [!question] Questions
> <3 brief questions based on the day>

---
*Generated by MonitorWatch*

## RULES
1. **ZERO EMOJIS**.
2. **TITLE**: Must be descriptive of main activity, NOT "Daily Log" or date-based.
3. **FIX OCR ERRORS**: WhitsApp→WhatsApp, Antigr4vity→Antigravity, Wi$pr→Whisper, Xrodg→Xcode, Tennlno1→Terminal
4. **BE COMPREHENSIVE**: Include all relevant details from the summaries.
5. **TAGS**: Use tags like #tag within context.
6. **LINKS**: Use [[WikiLinks]] to connect concepts.
7. **LANGUAGE**: Output strictly in English.
`;
}

function buildPortuguesePromptFromSummaries(formattedDate: string, summariesText: string, noteNumber?: number): string {
    const generatedAt = new Date().toISOString().replace('T', ' ').slice(0, 19);
    const noteNumberStr = noteNumber ? ` #${noteNumber}` : '';
    
    return `
# INSTRUÇÕES DE GERAÇÃO

Você é um assistente pessoal integrado ao Obsidian.
Crie uma nota diária completa a partir dos resumos por hora abaixo.

## RESUMOS POR HORA
${summariesText}

---

## FORMATO DE SAÍDA (MARKDOWN)

**FORMATO DO TITULO:**
# <Assunto/Tema Principal do Dia>${noteNumberStr}

*${formattedDate} - Gerado em: ${generatedAt}*

O titulo deve descrever o FOCO PRINCIPAL do dia baseado nos resumos. Exemplos:
- "Desenvolvimento e Testes do MonitorWatch"
- "Sessao de Refatoracao do Backend"
- "Reunioes com Clientes e Planejamento"
NAO use titulos genericos como "Diario" ou "Daily Log".

Gere apenas o conteúdo Markdown abaixo, sem conversas.

## Resumo
<Narrativa detalhada sobre o dia cobrindo todas as atividades, projetos, aprendizados e conversas. Use tags (#projeto, #tech) e links ([[Link]]) naturalmente no meio das frases.>

## Entregas & Foco
> [!SUCCESS] Highlights
> - [x] <Conquista 1>
> - [x] <Conquista 2>
> - [x] <Mais conquistas baseadas nos resumos>

### Projetos & Tarefas
- **<Nome do Projeto>**: <O que foi feito>
- **<Outro Projeto>**: <Detalhes>

## Reuniões & Insights
> [!quote] Conversas
> <Resumo de reuniões e conversas se houver>

## Aprendizado
- [[Conceito]] estudado.
- #tech/tema explorado.
- <Mais aprendizados>

## Reflexão
> [!question] Perguntas
> <3 perguntas breves baseadas no dia>

---
*Gerado por MonitorWatch*

## REGRAS
1. **ZERO EMOJIS**.
2. **TITULO**: Deve ser descritivo da atividade principal, NAO "Diario" ou baseado em data.
3. **CORRIGIR ERROS DE OCR**: WhitsApp→WhatsApp, Antigr4vity→Antigravity, Wi$pr→Whisper, Xrodg→Xcode, Tennlno1→Terminal
4. **SEJA COMPLETO**: Inclua todos os detalhes relevantes dos resumos.
5. **TAGS**: Use tags como #tag dentro do contexto.
6. **LINKS**: Use [[WikiLinks]] para conectar conceitos.
7. **IDIOMA**: Saída estritamente em Português do Brasil.
`;
}

function buildPrompt(activities: Activity[], transcripts: Transcript[], date: string, language: string, noteNumber?: number): string {
    const locale = language === 'pt' ? 'pt-BR' : 'en-US';
    const formattedDate = new Date(date).toLocaleDateString(locale);

    // Sort activities by timestamp
    const sortedActivities = [...activities].sort((a, b) => 
        new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
    );

    // Extract meaningful content: window titles and OCR text
    const allTitles: string[] = [];
    const allOcrContent: string[] = [];
    
    for (const activity of sortedActivities) {
        if (activity.window_title) {
            allTitles.push(activity.window_title);
        }
        if (activity.ocr_text) {
            allOcrContent.push(activity.ocr_text);
        }
    }

    // Dedupe titles but keep order
    const uniqueTitles = [...new Set(allTitles)];

    // Build content summary
    let activitiesSummary = '\n## Window Titles (what was open)\n';
    activitiesSummary += uniqueTitles.join('\n') + '\n';
    
    activitiesSummary += '\n## Screen Content (what was visible)\n';
    activitiesSummary += allOcrContent.join('\n---\n') + '\n';

    // Build transcripts
    let transcriptsSummary = '';
    if (transcripts.length > 0) {
        transcriptsSummary = '\n## Conversations & Audio\n';
        const sortedTranscripts = [...transcripts].sort((a, b) => 
            new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime()
        );
        for (const t of sortedTranscripts) {
            transcriptsSummary += `${t.text}\n\n`;
        }
    }

    if (language === 'pt') {
        return buildPortuguesePrompt(formattedDate, activitiesSummary, transcriptsSummary, noteNumber);
    }
    
    return buildEnglishPrompt(formattedDate, activitiesSummary, transcriptsSummary, noteNumber);
}

function buildEnglishPrompt(formattedDate: string, activitiesSummary: string, transcriptsSummary: string, noteNumber?: number): string {
    const noteTitle = noteNumber ? `# Daily Log: ${formattedDate} #${noteNumber}` : `# Daily Log: ${formattedDate}`;
    
    return `
# GENERATION INSTRUCTIONS

You are a personal assistant integrated with Obsidian.
Analyze the logs and create a direct, professional, and clean daily note.

## INPUT DATA
Date: ${formattedDate}

### ACTIVITIES
${activitiesSummary}

### TRANSCRIPTS
${transcriptsSummary}

---

## OUTPUT FORMAT (MARKDOWN)

Generate only the Markdown content below, no conversation.

${noteTitle}

## Summary
<Narrative paragraph about the day. Use tags (#project, #tech) and links ([[Link]]) naturally within sentences.>

## Deliverables & Focus
> [!SUCCESS] Highlights
> - [x] <Achievement 1>
> - [x] <Achievement 2>

### Technical Details
- **Project X**: ...
- **Tools**: ...

## Meetings & Insights
> [!quote] Conversations
> <Summary if there are transcripts.>

## Learning
- [[Concept]] studied.
- #tech/topic explored.

## Reflection
> [!question] Questions
> <3 brief questions.>

---
*Generated by MonitorWatch*

## RULES
1. **ZERO EMOJIS**.
2. **TAGS**: Use tags like #tag only within context or lists.
3. **LINKS**: Use [[WikiLinks]] to connect concepts.
4. **LANGUAGE**: Output strictly in English.
`;
}

function buildPortuguesePrompt(formattedDate: string, activitiesSummary: string, transcriptsSummary: string, noteNumber?: number): string {
    const noteTitle = noteNumber ? `# Diario: ${formattedDate} #${noteNumber}` : `# Diario: ${formattedDate}`;
    
    return `
# INSTRUÇÕES DE GERAÇÃO

Você é um assistente pessoal integrado ao Obsidian.
Analise os logs e crie uma nota diária direta, profissional e limpa.

## DADOS DE ENTRADA
Data: ${formattedDate}

### ATIVIDADES
${activitiesSummary}

### TRANSCRIÇÕES
${transcriptsSummary}

---

## FORMATO DE SAÍDA (MARKDOWN)

Gere apenas o conteúdo Markdown abaixo, sem conversas.

${noteTitle}

## Resumo
<Parágrafo narrativo sobre o dia. Use tags (#projeto, #tech) e links ([[Link]]) naturalmente no meio das frases.>

## Entregas & Foco
> [!SUCCESS] Highlights
> - [x] <Conquista 1>
> - [x] <Conquista 2>

### Detalhes Técnicos
- **Projeto X**: ...
- **Ferramentas**: ...

## Reuniões & Insights
> [!quote] Conversas
> <Resumo se houver transcrições.>

## Aprendizado
- [[Conceito]] estudado.
- #tech/tema explorado.

## Reflexão
> [!question] Perguntas
> <3 perguntas breves.>

---
*Gerado por MonitorWatch*

## REGRAS
1. **ZERO EMOJIS**.
2. **TAGS**: Use tags como #tag apenas dentro do contexto ou listas.
3. **LINKS**: Use [[WikiLinks]] para conectar conceitos.
4. **IDIOMA**: Saída estritamente em Português do Brasil.
`;
}

export async function generateMeetingNoteWithAI(
    activities: Activity[],
    transcripts: Transcript[],
    context: string,
    date: string,
    env: Env,
    aiConfig?: { provider: string; openRouterKey?: string; model?: string; language?: string }
): Promise<{ content: string; title: string }> {
    const language = aiConfig?.language || 'en';
    const prompt = buildMeetingPrompt(activities, transcripts, context, date, language);
    const model = aiConfig?.model || 'google/gemini-2.0-flash-001';
    const apiKey = aiConfig?.openRouterKey || '';

    const text = await callOpenRouter(prompt, apiKey, model);

    // Attempt to extract suggested title from response
    const titleMatch = text.match(/^#\s+(?:.*?)?\s*(.+)$/m);
    let title = context;
    if (titleMatch && titleMatch[1]) {
        title = titleMatch[1].trim()
            .replace(/^[🎙💻]\s*/, '')
            .replace(/[<>:"/\\|?*]/g, '')
            .trim();
    }

    if (!title || title.length < 2) {
        title = language === 'pt' 
            ? `Nota - ${new Date().toLocaleTimeString('pt-BR')}`
            : `Note - ${new Date().toLocaleTimeString('en-US')}`;
    }

    return { content: text, title };
}

function buildMeetingPrompt(activities: Activity[], transcripts: Transcript[], context: string, date: string, language: string): string {
    let transcriptsSummary = language === 'pt' ? 'Nenhuma transcrição disponível.' : 'No transcripts available.';
    if (transcripts.length > 0) {
        transcriptsSummary = '';
        for (const t of transcripts) {
            transcriptsSummary += `- [${t.source}]: ${t.text}\n`;
        }
    }

    if (language === 'pt') {
        return buildPortugueseMeetingPrompt(activities, transcriptsSummary, context, date);
    }
    
    return buildEnglishMeetingPrompt(activities, transcriptsSummary, context, date);
}

function buildEnglishMeetingPrompt(activities: Activity[], transcriptsSummary: string, context: string, date: string): string {
    return `
# SYSTEM: CONTEXT AWARE NOTE GENERATOR

You are an expert personal data analyst integrated into Obsidian.
You receive a log of the last 2 hours of user activity (Apps & Audio).
Your goal is to identify the **Current Logical Session** and generate a high-quality Markdown note for it.

## INPUT DATA
Context Hint: "${context}" (Trigger Phrase)
Date: ${new Date(date).toLocaleString('en-US')}

### TRANSCRIPTS (Audio)
${transcriptsSummary}

### ACTIVITIES (App Usage)
${activities.map(a => `- [${new Date(a.timestamp).toLocaleTimeString('en-US')}] ${a.app_name}: ${a.window_title}`).join('\n')}

---

## YOUR TASK

1.  **SEGMENTATION**: Scan the logs backwards from the end. Identify when the *current* specific context started.
    *   If words like "Meeting", "Daily", "Sync" appear in audio -> It's a **Meeting**.
    *   If heavy usage of VS Code, Terminal, Xcode -> It's a **Coding Session**.
    *   If usage of Browser, YouTube, Reading -> It's a **Research/Study Session**.

2.  **EXTRACTION**: Extract *only* the information relevant to this specific identified session.

3.  **GENERATION**: Generate a specific Markdown note based on the detected type.

---

## OUTPUT FORMATS

### MODE A: MEETING (Default if audio conversation detected)
\`\`\`markdown
---
date: ${new Date(date).toISOString().split('T')[0]}
type: meeting
participants: [Me, <Detect>]
tags: [meeting, <Output>]
---

# <Title based on Topic>

## Executive Summary
<Brief summary of what was discussed>

## Key Points
- <Bullet point>
- <Bullet point>

## Action Items
> [!todo] Actions
> - [ ] <Action 1>

\`\`\`

### MODE B: CODING/WORK SESSION (If mostly App usage/Technical)
\`\`\`markdown
---
date: ${new Date(date).toISOString().split('T')[0]}
type: dev-log
tags: [dev, <Output>]
---

# <Title based on Project/Activity>

## Context
<What was being worked on>

## Changes & Details
- **<App/File>**: <Details based on Window Titles/OCR>

## Insights/Decisions
> [!tip] Tech Note
> <Technical decision or learning>
\`\`\`

---

## CRITICAL RULES
1.  **Auto-Detect Start Time**: Do not just summarize the whole 2 hours. Find the logical start.
2.  **English**: Output strictly in English.
3.  **No Fluff**: Be direct and concise.
4.  **No Emojis**: Zero emojis in output.
5.  **Output ONLY Markdown**: No conversational text.
`;
}

function buildPortugueseMeetingPrompt(activities: Activity[], transcriptsSummary: string, context: string, date: string): string {
    return `
# SISTEMA: GERADOR DE NOTAS CONTEXTUAL

Você é um analista de dados pessoais especializado integrado ao Obsidian.
Você recebe um log das últimas 2 horas de atividade do usuário (Apps e Áudio).
Seu objetivo é identificar a **Sessão Lógica Atual** e gerar uma nota Markdown de alta qualidade.

## DADOS DE ENTRADA
Dica de Contexto: "${context}" (Frase Gatilho)
Data: ${new Date(date).toLocaleString('pt-BR')}

### TRANSCRIÇÕES (Áudio)
${transcriptsSummary}

### ATIVIDADES (Uso de Apps)
${activities.map(a => `- [${new Date(a.timestamp).toLocaleTimeString('pt-BR')}] ${a.app_name}: ${a.window_title}`).join('\n')}

---

## SUA TAREFA

1.  **SEGMENTAÇÃO**: Analise os logs de trás para frente. Identifique quando o contexto atual começou.
    *   Se palavras como "Reunião", "Daily", "Alinhamento" aparecem no áudio -> É uma **Reunião**.
    *   Se uso intenso de VS Code, Terminal, Xcode -> É uma **Sessão de Código**.
    *   Se uso de Browser, YouTube, Leitura -> É uma **Sessão de Pesquisa/Estudo**.

2.  **EXTRAÇÃO**: Extraia *apenas* informações relevantes para esta sessão específica.

3.  **GERAÇÃO**: Gere uma nota Markdown específica baseada no tipo detectado.

---

## FORMATOS DE SAÍDA

### MODO A: REUNIÃO (Padrão se conversa detectada)
\`\`\`markdown
---
date: ${new Date(date).toISOString().split('T')[0]}
type: meeting
participants: [Eu, <Detectar>]
tags: [meeting, <Output>]
---

# <Título baseado no Tópico>

## Resumo Executivo
<Breve resumo do que foi discutido>

## Pontos Principais
- <Ponto>
- <Ponto>

## Action Items
> [!todo] Ações
> - [ ] <Ação 1>

\`\`\`

### MODO B: SESSÃO DE CÓDIGO/TRABALHO (Se principalmente uso técnico)
\`\`\`markdown
---
date: ${new Date(date).toISOString().split('T')[0]}
type: dev-log
tags: [dev, <Output>]
---

# <Título baseado no Projeto/Atividade>

## Contexto
<O que estava sendo trabalhado>

## Alterações & Detalhes
- **<App/Arquivo>**: <Detalhes baseados em Títulos/OCR>

## Insights/Decisões
> [!tip] Nota Técnica
> <Decisão técnica ou aprendizado>
\`\`\`

---

## REGRAS CRÍTICAS
1.  **Auto-Detectar Início**: Não resuma as 2 horas inteiras. Encontre o início lógico.
2.  **Português-Brasil**: Saída estritamente em PT-BR.
3.  **Sem Enrolação**: Seja direto e conciso.
4.  **Sem Emojis**: Zero emojis na saída.
5.  **Apenas Markdown**: Sem texto conversacional.
`;
}
