name: MonitorWatch Branch Protection

on:
  - pull_request
  - push

rules:
  - name: Main Branch Protection
    enforcement: active
    conditions:
      ref_name:
        include:
          - main
          - master
    parameters:
      require_signed_commits: true
      require_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: true
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: false
        bypass_pull_request_allowances:
          users: []
          teams: []
          apps: []
      restrictions:
        users: []
        teams: []
        apps: []

  - name: Production Branch Protection
    enforcement: active
    conditions:
      ref_name:
        include:
          - production
          - release/*
    parameters:
      require_signed_commits: true
      require_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_linear_history: true
      required_status_checks:
        strict: true
        contexts:
          - "Build"
          - "Test"
          - "Lint"
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          users: []
          teams: []
          apps: []
      restrictions:
        users: []
        teams: []
        apps: []

  - name: Require Approval for Sensitive Files
    enforcement: active
    conditions:
      ref_name:
        include:
          - '**'
    parameters:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
      required_status_checks:
        strict: false
        contexts: []

  - name: Prevent Deletion of Critical Files
    enforcement: active
    conditions:
      ref_name:
        include:
          - '**'
    parameters:
      restrictions:
        users:
          - ianfr13
        teams: []
        apps: []
